### ISSUE TITLE
about signup option

### ISSUE THREAD

**Issue by thekubilay** [serversideup/roastandbrew#14]
thank you for the SPA. it's really helpful and also nice tutorial side. 

I have a question about sign up option. I check out the live app and couldn't see the sign up option there. Do we need to add it by selves, is it possible to add it. Because if I understand it correctly you are deleting Laravel's auth option. also, changing the driver.  

could you guide me about adding sign up in this app? thank you.

**Comment by Avikky** [comment]
There is no signup option because all the login and signup are handled by the laravel socialite.
how this work is that when the user clicks on any of the available social logins, what socialite does is to check if the user exists based on the data it collected from the user's social media account if the user exists it will log in the user but if the user does not exist it will sign the user up and login automatically

**Comment by jaydrogers** [comment]
Thanks for chiming in @Avikky.

Just a heads up, we just launched a brand new version of Roast on https://roastandbrew.coffee

This repository no longer reflects what is running on the site. We have a totally different approach on how we launched this new version and we will be talking about this in our upcoming book: https://serversideup.net/ultimate-guide-to-building-apis-and-spas-with-laravel-and-vuejs/

We're hoping to have the book released in the next few weeks, but I know @danpastori mentioned that he may be talking about Social Auth.

More details to come shortly. Jump on our mailing list from the link above if you are interested!
